name: Push to GCR GitHub Action
on: [push]
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:      
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/1070274539288/locations/global/workloadIdentityPools/my-pool/providers/github-provider
          service_account: github-action@microservice-nodejs.iam.gserviceaccount.com
      - name: run ls
        run: |
          ls
          ls -la    
